import { Local } from "./Misc";

const Locals = () => {
    return [
        { langabr: 'en', local: 'en-US', language: 'English (United States)' },
        { langabr: 'pt', local: 'pt-BR', language: 'Portuguese (Brazil)' },
        { langabr: 'es', local: 'es-AR', language: 'Spanish (Argentina)' },
        { langabr: 'es', local: 'es-ES', language: 'Spanish (Spain)' },
        { langabr: 'es', local: 'es-MX', language: 'Spanish (Mexico)' },
        { langabr: 'es', local: 'es-PY', language: 'Spanish (Paraguay)' },

        { langabr: 'de', local: 'de-AT', language: 'German (Austria)' },
        { langabr: 'de', local: 'de-BE', language: 'German (Belgium)' },
        { langabr: 'de', local: 'de-CH', language: 'German (Switzerland)' },
        { langabr: 'de', local: 'de-DE', language: 'German (Germany)' },
        { langabr: 'de', local: 'de-IT', language: 'German (Italy)' },
        { langabr: 'de', local: 'de-LI', language: 'German (Liechtenstein)' },
        { langabr: 'de', local: 'de-LU', language: 'German (Luxembourg)' },

        { langabr: 'ar', local: 'ar-AE', language: 'Arabic (United Arab Emirates)' },
        { langabr: 'ar', local: 'ar-BH', language: 'Arabic (Bahrain)' },
        { langabr: 'ar', local: 'ar-DJ', language: 'Arabic (Djibouti)' },
        { langabr: 'ar', local: 'ar-DZ', language: 'Arabic (Algeria)' },
        { langabr: 'ar', local: 'ar-EG', language: 'Arabic (Egypt)' },
        { langabr: 'ar', local: 'ar-EH', language: 'Arabic (Western Sahara)' },
        { langabr: 'ar', local: 'ar-ER', language: 'Arabic (Eritrea)' },
        { langabr: 'ar', local: 'ar-IL', language: 'Arabic (Israel)' },
        { langabr: 'ar', local: 'ar-IQ', language: 'Arabic (Iraq)' },
        { langabr: 'ar', local: 'ar-JO', language: 'Arabic (Jordan)' },
        { langabr: 'ar', local: 'ar-KM', language: 'Arabic (Comoros)' },
        { langabr: 'ar', local: 'ar-KW', language: 'Arabic (Kuwait)' },
        { langabr: 'ar', local: 'ar-LB', language: 'Arabic (Lebanon)' },
        { langabr: 'ar', local: 'ar-LY', language: 'Arabic (Libya)' },
        { langabr: 'ar', local: 'ar-MA', language: 'Arabic (Morocco)' },
        { langabr: 'ar', local: 'ar-MR', language: 'Arabic (Mauritania)' },
        { langabr: 'ar', local: 'ar-OM', language: 'Arabic (Oman)' },
        { langabr: 'ar', local: 'ar-PS', language: 'Arabic (Palestinian Territories)' },
        { langabr: 'ar', local: 'ar-QA', language: 'Arabic (Qatar)' },
        { langabr: 'ar', local: 'ar-SA', language: 'Arabic (Saudi Arabia)' },
        { langabr: 'ar', local: 'ar-SD', language: 'Arabic (Sudan)' },
        { langabr: 'ar', local: 'ar-SO', language: 'Arabic (Somalia)' },
        { langabr: 'ar', local: 'ar-SS', language: 'Arabic (South Sudan)' },
        { langabr: 'ar', local: 'ar-SY', language: 'Arabic (Syria)' },
        { langabr: 'ar', local: 'ar-TD', language: 'Arabic (Chad)' },
        { langabr: 'ar', local: 'ar-TN', language: 'Arabic (Tunisia)' },
        { langabr: 'ar', local: 'ar-YE', language: 'Arabic (Yemen)' },
        { langabr: 'as', local: 'as-IN', language: 'Assamese (India)' },
        { langabr: 'asa', local: 'asa-TZ', language: 'Asu (Tanzania)' },
        { langabr: 'az', local: 'az-Cyrl', language: 'Azerbaijani (Cyrillic)' },
        { langabr: 'az', local: 'az-Cyrl-AZ', language: 'Azerbaijani (Cyrillic, Azerbaijan)' },
        { langabr: 'az', local: 'az-Latn', language: 'Azerbaijani (Latin)' },
        { langabr: 'az', local: 'az-Latn-AZ', language: 'Azerbaijani (Latin, Azerbaijan)' },
        { langabr: 'bas', local: 'bas-CM', language: 'Basaa (Cameroon)' },
        { langabr: 'be', local: 'be-BY', language: 'Belarusian (Belarus)' },
        { langabr: 'bem', local: 'bem-ZM', language: 'Bemba (Zambia)' },
        { langabr: 'bez', local: 'bez-TZ', language: 'Bena (Tanzania)' },
        { langabr: 'bg', local: 'bg-BG', language: 'Bulgarian (Bulgaria)' },
        { langabr: 'bm', local: 'bm-ML', language: 'Bambara (Mali)' },
        { langabr: 'bn', local: 'bn-BD', language: 'Bangla (Bangladesh)' },
        { langabr: 'bn', local: 'bn-BD', language: 'Bengali (Bangladesh)' },
        { langabr: 'bn', local: 'bn-IN', language: 'Bangla (India)' },
        { langabr: 'bn', local: 'bn-IN', language: 'Bengali (India)' },
        { langabr: 'bo', local: 'bo-CN', language: 'Tibetan (China)' },
        { langabr: 'bo', local: 'bo-IN', language: 'Tibetan (India)' },
        { langabr: 'br', local: 'br-FR', language: 'Breton (France)' },
        { langabr: 'brx', local: 'brx-IN', language: 'Bodo (India)' },
        { langabr: 'bs', local: 'bs-Cyrl', language: 'Bosnian (Cyrillic)' },
        { langabr: 'bs', local: 'bs-Cyrl-BA', language: 'Bosnian (Cyrillic, Bosnia & Herzegovina)' },
        { langabr: 'bs', local: 'bs-Latn', language: 'Bosnian (Latin)' },
        { langabr: 'bs', local: 'bs-Latn-BA', language: 'Bosnian (Latin, Bosnia & Herzegovina)' },
        { langabr: 'ca', local: 'ca-AD', language: 'Catalan (Andorra)' },
        { langabr: 'ca', local: 'ca-ES', language: 'Catalan (Spain)' },
        { langabr: 'ca', local: 'ca-FR', language: 'Catalan (France)' },
        { langabr: 'ca', local: 'ca-IT', language: 'Catalan (Italy)' },
        { langabr: 'ce', local: 'ce-RU', language: 'Chechen (Russia)' },
        { langabr: 'cgg', local: 'cgg-UG', language: 'Chiga (Uganda)' },
        { langabr: 'chr', local: 'chr-US', language: 'Cherokee (United States)' },
        { langabr: 'cs', local: 'cs-CZ', language: 'Czech (Czech Republic)' },
        { langabr: 'cy', local: 'cy-GB', language: 'Welsh (United Kingdom)' },
        { langabr: 'da', local: 'da-DK', language: 'Danish (Denmark)' },
        { langabr: 'dav', local: 'dav-KE', language: 'Taita (Kenya)' },
        
        { langabr: 'dje', local: 'dje-NE', language: 'Zarma (Niger)' },
        { langabr: 'dsb', local: 'dsb-DE', language: 'Lower Sorbian (Germany)' },
        { langabr: 'dua', local: 'dua-CM', language: 'Duala (Cameroon)' },
        { langabr: 'dyo', local: 'dyo-SN', language: 'Jola-Fonyi (Senegal)' },
        { langabr: 'dz', local: 'dz-BT', language: 'Dzongkha (Bhutan)' },
        { langabr: 'ebu', local: 'ebu-KE', language: 'Embu (Kenya)' },
        { langabr: 'ee', local: 'ee-GH', language: 'Ewe (Ghana)' },
        { langabr: 'ee', local: 'ee-TG', language: 'Ewe (Togo)' },
        { langabr: 'el', local: 'el-CY', language: 'Greek (Cyprus)' },
        { langabr: 'el', local: 'el-GR', language: 'Greek (Greece)' },
        { langabr: 'en', local: 'en-AG', language: 'English (Antigua & Barbuda)' },
        { langabr: 'en', local: 'en-AI', language: 'English (Anguilla)' },
        { langabr: 'en', local: 'en-AS', language: 'English (American Samoa)' },
        { langabr: 'en', local: 'en-AT', language: 'English (Austria)' },
        { langabr: 'en', local: 'en-AU', language: 'English (Australia)' },
        { langabr: 'en', local: 'en-BB', language: 'English (Barbados)' },
        { langabr: 'en', local: 'en-BE', language: 'English (Belgium)' },
        { langabr: 'en', local: 'en-BI', language: 'English (Burundi)' },
        { langabr: 'en', local: 'en-BM', language: 'English (Bermuda)' },
        { langabr: 'en', local: 'en-BS', language: 'English (Bahamas)' },
        { langabr: 'en', local: 'en-BW', language: 'English (Botswana)' },
        { langabr: 'en', local: 'en-BZ', language: 'English (Belize)' },
        { langabr: 'en', local: 'en-CA', language: 'English (Canada)' },
        { langabr: 'en', local: 'en-CC', language: 'English (Cocos [Keeling] Islands)' },
        { langabr: 'en', local: 'en-CH', language: 'English (Switzerland)' },
        { langabr: 'en', local: 'en-CK', language: 'English (Cook Islands)' },
        { langabr: 'en', local: 'en-CM', language: 'English (Cameroon)' },
        { langabr: 'en', local: 'en-CX', language: 'English (Christmas Island)' },
        { langabr: 'en', local: 'en-CY', language: 'English (Cyprus)' },
        { langabr: 'en', local: 'en-DE', language: 'English (Germany)' },
        { langabr: 'en', local: 'en-DG', language: 'English (Diego Garcia)' },
        { langabr: 'en', local: 'en-DK', language: 'English (Denmark)' },
        { langabr: 'en', local: 'en-DM', language: 'English (Dominica)' },
        { langabr: 'en', local: 'en-ER', language: 'English (Eritrea)' },
        { langabr: 'en', local: 'en-FI', language: 'English (Finland)' },
        { langabr: 'en', local: 'en-FJ', language: 'English (Fiji)' },
        { langabr: 'en', local: 'en-FK', language: 'English (Falkland Islands)' },
        { langabr: 'en', local: 'en-FM', language: 'English (Micronesia)' },
        { langabr: 'en', local: 'en-GB', language: 'English (United Kingdom)' },
        { langabr: 'en', local: 'en-GD', language: 'English (Grenada)' },
        { langabr: 'en', local: 'en-GG', language: 'English (Guernsey)' },
        { langabr: 'en', local: 'en-GH', language: 'English (Ghana)' },
        { langabr: 'en', local: 'en-GI', language: 'English (Gibraltar)' },
        { langabr: 'en', local: 'en-GM', language: 'English (Gambia)' },
        { langabr: 'en', local: 'en-GU', language: 'English (Guam)' },
        { langabr: 'en', local: 'en-GY', language: 'English (Guyana)' },
        { langabr: 'en', local: 'en-HK', language: 'English (Hong Kong SAR China)' },
        { langabr: 'en', local: 'en-IE', language: 'English (Ireland)' },
        { langabr: 'en', local: 'en-IL', language: 'English (Israel)' },
        { langabr: 'en', local: 'en-IM', language: 'English (Isle of Man)' },
        { langabr: 'en', local: 'en-IN', language: 'English (India)' },
        { langabr: 'en', local: 'en-IO', language: 'English (British Indian Ocean Territory)' },
        { langabr: 'en', local: 'en-JE', language: 'English (Jersey)' },
        { langabr: 'en', local: 'en-JM', language: 'English (Jamaica)' },
        { langabr: 'en', local: 'en-KE', language: 'English (Kenya)' },
        { langabr: 'en', local: 'en-KI', language: 'English (Kiribati)' },
        { langabr: 'en', local: 'en-KN', language: 'English (St. Kitts & Nevis)' },
        { langabr: 'en', local: 'en-KY', language: 'English (Cayman Islands)' },
        { langabr: 'en', local: 'en-LC', language: 'English (St. Lucia)' },
        { langabr: 'en', local: 'en-LR', language: 'English (Liberia)' },
        { langabr: 'en', local: 'en-LS', language: 'English (Lesotho)' },
        { langabr: 'en', local: 'en-MG', language: 'English (Madagascar)' },
        { langabr: 'en', local: 'en-MH', language: 'English (Marshall Islands)' },
        { langabr: 'en', local: 'en-MO', language: 'English (Macau SAR China)' },
        { langabr: 'en', local: 'en-MP', language: 'English (Northern Mariana Islands)' },
        { langabr: 'en', local: 'en-MS', language: 'English (Montserrat)' },
        { langabr: 'en', local: 'en-MT', language: 'English (Malta)' },
        { langabr: 'en', local: 'en-MU', language: 'English (Mauritius)' },
        { langabr: 'en', local: 'en-MW', language: 'English (Malawi)' },
        { langabr: 'en', local: 'en-MY', language: 'English (Malaysia)' },
        { langabr: 'en', local: 'en-NA', language: 'English (Namibia)' },
        { langabr: 'en', local: 'en-NF', language: 'English (Norfolk Island)' },
        { langabr: 'en', local: 'en-NG', language: 'English (Nigeria)' },
        { langabr: 'en', local: 'en-NL', language: 'English (Netherlands)' },
        { langabr: 'en', local: 'en-NR', language: 'English (Nauru)' },
        { langabr: 'en', local: 'en-NU', language: 'English (Niue)' },
        { langabr: 'en', local: 'en-NZ', language: 'English (New Zealand)' },
        { langabr: 'en', local: 'en-PG', language: 'English (Papua New Guinea)' },
        { langabr: 'en', local: 'en-PH', language: 'English (Philippines)' },
        { langabr: 'en', local: 'en-PK', language: 'English (Pakistan)' },
        { langabr: 'en', local: 'en-PN', language: 'English (Pitcairn Islands)' },
        { langabr: 'en', local: 'en-PR', language: 'English (Puerto Rico)' },
        { langabr: 'en', local: 'en-PW', language: 'English (Palau)' },
        { langabr: 'en', local: 'en-RW', language: 'English (Rwanda)' },
        { langabr: 'en', local: 'en-SB', language: 'English (Solomon Islands)' },
        { langabr: 'en', local: 'en-SC', language: 'English (Seychelles)' },
        { langabr: 'en', local: 'en-SD', language: 'English (Sudan)' },
        { langabr: 'en', local: 'en-SE', language: 'English (Sweden)' },
        { langabr: 'en', local: 'en-SG', language: 'English (Singapore)' },
        { langabr: 'en', local: 'en-SH', language: 'English (St. Helena)' },
        { langabr: 'en', local: 'en-SI', language: 'English (Slovenia)' },
        { langabr: 'en', local: 'en-SL', language: 'English (Sierra Leone)' },
        { langabr: 'en', local: 'en-SS', language: 'English (South Sudan)' },
        { langabr: 'en', local: 'en-SX', language: 'English (Sint Maarten)' },
        { langabr: 'en', local: 'en-SZ', language: 'English (Swaziland)' },
        { langabr: 'en', local: 'en-TC', language: 'English (Turks & Caicos Islands)' },
        { langabr: 'en', local: 'en-TK', language: 'English (Tokelau)' },
        { langabr: 'en', local: 'en-TO', language: 'English (Tonga)' },
        { langabr: 'en', local: 'en-TT', language: 'English (Trinidad & Tobago)' },
        { langabr: 'en', local: 'en-TV', language: 'English (Tuvalu)' },
        { langabr: 'en', local: 'en-TZ', language: 'English (Tanzania)' },
        { langabr: 'en', local: 'en-UG', language: 'English (Uganda)' },
        { langabr: 'en', local: 'en-UM', language: 'English (U.S. Outlying Islands)' },
      
        { langabr: 'en', local: 'en-VC', language: 'English (St. Vincent & Grenadines)' },
        { langabr: 'en', local: 'en-VG', language: 'English (British Virgin Islands)' },
        { langabr: 'en', local: 'en-VI', language: 'English (U.S. Virgin Islands)' },
        { langabr: 'en', local: 'en-VU', language: 'English (Vanuatu)' },
        { langabr: 'en', local: 'en-WS', language: 'English (Samoa)' },
        { langabr: 'en', local: 'en-ZA', language: 'English (South Africa)' },
        { langabr: 'en', local: 'en-ZM', language: 'English (Zambia)' },
        { langabr: 'en', local: 'en-ZW', language: 'English (Zimbabwe)' },
        
        { langabr: 'es', local: 'es-BO', language: 'Spanish (Bolivia)' },
        { langabr: 'es', local: 'es-BR', language: 'Spanish (Brazil)' },
        { langabr: 'es', local: 'es-BZ', language: 'Spanish (Belize)' },
        { langabr: 'es', local: 'es-CL', language: 'Spanish (Chile)' },
        { langabr: 'es', local: 'es-CO', language: 'Spanish (Colombia)' },
        { langabr: 'es', local: 'es-CR', language: 'Spanish (Costa Rica)' },
        { langabr: 'es', local: 'es-CU', language: 'Spanish (Cuba)' },
        { langabr: 'es', local: 'es-DO', language: 'Spanish (Dominican Republic)' },
        { langabr: 'es', local: 'es-EA', language: 'Spanish (Ceuta & Melilla' },
        { langabr: 'es', local: 'es-EC', language: 'Spanish (Ecuador)' },
        
        { langabr: 'es', local: 'es-GQ', language: 'Spanish (Equatorial Guinea)' },
        { langabr: 'es', local: 'es-GT', language: 'Spanish (Guatemala)' },
        { langabr: 'es', local: 'es-HN', language: 'Spanish (Honduras)' },
        { langabr: 'es', local: 'es-IC', language: 'Spanish (Canary Islands)' },




        { langabr: 'es', local: 'es-NI', language: 'Spanish (Nicaragua)' },
        { langabr: 'es', local: 'es-PA', language: 'Spanish (Panama)' },
        { langabr: 'es', local: 'es-PE', language: 'Spanish (Peru)' },
        { langabr: 'es', local: 'es-PR', language: 'Spanish (Puerto Rico)' },
       
        { langabr: 'es', local: 'es-SV', language: 'Spanish (El Salvador)' },
        { langabr: 'es', local: 'es-US', language: 'Spanish (United States)' },
        { langabr: 'es', local: 'es-UY', language: 'Spanish (Uruguay)' },
        { langabr: 'es', local: 'es-VE', language: 'Spanish (Venezuela)' },
        { langabr: 'et', local: 'et-EE', language: 'Estonian (Estonia)' },
        { langabr: 'eu', local: 'eu-ES', language: 'Basque (Spain)' },
        { langabr: 'ewo', local: 'ewo-CM', language: 'Ewondo (Cameroon)' },
        { langabr: 'fa', local: 'fa-AF', language: 'Persian (Afghanistan)' },
        { langabr: 'fa', local: 'fa-IR', language: 'Persian (Iran)' },
        { langabr: 'ff', local: 'ff-CM', language: 'Fulah (Cameroon' },
        { langabr: 'ff', local: 'ff-GN', language: 'Fulah (Guinea)' },
        { langabr: 'ff', local: 'ff-MR', language: 'Fulah (Mauritania)' },
        { langabr: 'ff', local: 'ff-SN', language: 'Fulah (Senegal)' },
        { langabr: 'fi', local: 'fi-FI', language: 'Finnish (Finland)' },
        { langabr: 'fil', local: 'fil-PH', language: 'Filipino (Philippines)' },
        { langabr: 'fo', local: 'fo-DK', language: 'Faroese (Denmark)' },
        { langabr: 'fo', local: 'fo-FO', language: 'Faroese (Faroe Islands)' },
        { langabr: 'fr', local: 'fr-BE', language: 'French (Belgium)' },
        { langabr: 'fr', local: 'fr-BF', language: 'French (Burkina Faso)' },
        { langabr: 'fr', local: 'fr-BI', language: 'French (Burundi)' },
        { langabr: 'fr', local: 'fr-BJ', language: 'French (Benin)' },
        { langabr: 'fr', local: 'fr-BL', language: 'French (St. Barthélemy)' },
        { langabr: 'fr', local: 'fr-CA', language: 'French (Canada)' },
        { langabr: 'fr', local: 'fr-CD', language: 'French (Congo - Kinshasa)' },
        { langabr: 'fr', local: 'fr-CF', language: 'French (Central African Republic)' },
        { langabr: 'fr', local: 'fr-CG', language: 'French (Congo - Brazzaville)' },
        { langabr: 'fr', local: 'fr-CH', language: 'French (Switzerland)' },
        { langabr: 'fr', local: 'fr-CI', language: 'French (Côte d’Ivoire)' },
        { langabr: 'fr', local: 'fr-CM', language: 'French (Cameroon)' },
        { langabr: 'fr', local: 'fr-DJ', language: 'French (Djibouti)' },
        { langabr: 'fr', local: 'fr-DZ', language: 'French (Algeria)' },
        { langabr: 'fr', local: 'fr-FR', language: 'French (France)' },
        { langabr: 'fr', local: 'fr-GA', language: 'French (Gabon)' },
        { langabr: 'fr', local: 'fr-GF', language: 'French (French Guiana)' },
        { langabr: 'fr', local: 'fr-GN', language: 'French (Guinea)' },
        { langabr: 'fr', local: 'fr-GP', language: 'French (Guadeloupe)' },
        { langabr: 'fr', local: 'fr-GQ', language: 'French (Equatorial Guinea)' },
        { langabr: 'fr', local: 'fr-HT', language: 'French (Haiti)' },
        { langabr: 'fr', local: 'fr-KM', language: 'French (Comoros)' },
        { langabr: 'fr', local: 'fr-LU', language: 'French (Luxembourg)' },
        { langabr: 'fr', local: 'fr-MA', language: 'French (Morocco)' },
        { langabr: 'fr', local: 'fr-MC', language: 'French (Monaco)' },
        { langabr: 'fr', local: 'fr-MF', language: 'French (St. Martin)' },
        { langabr: 'fr', local: 'fr-MG', language: 'French (Madagascar)' },
        { langabr: 'fr', local: 'fr-ML', language: 'French (Mali)' },
        { langabr: 'fr', local: 'fr-MQ', language: 'French (Martinique)' },
        { langabr: 'fr', local: 'fr-MR', language: 'French (Mauritania)' },
        { langabr: 'fr', local: 'fr-MU', language: 'French (Mauritius)' },
        { langabr: 'fr', local: 'fr-NC', language: 'French (New Caledonia)' },
        { langabr: 'fr', local: 'fr-NE', language: 'French (Niger)' },
        { langabr: 'fr', local: 'fr-PF', language: 'French (French Polynesia)' },
        { langabr: 'fr', local: 'fr-PM', language: 'French (St. Pierre & Miquelon)' },
        { langabr: 'fr', local: 'fr-RE', language: 'French (Réunion)' },
        { langabr: 'fr', local: 'fr-RW', language: 'French (Rwanda)' },
        { langabr: 'fr', local: 'fr-SC', language: 'French (Seychelles)' },
        { langabr: 'fr', local: 'fr-SN', language: 'French (Senegal)' },
        { langabr: 'fr', local: 'fr-SY', language: 'French (Syria)' },
        { langabr: 'fr', local: 'fr-TD', language: 'French (Chad)' },
        { langabr: 'fr', local: 'fr-TG', language: 'French (Togo)' },
        { langabr: 'fr', local: 'fr-TN', language: 'French (Tunisia)' },
        { langabr: 'fr', local: 'fr-VU', language: 'French (Vanuatu)' },
        { langabr: 'fr', local: 'fr-WF', language: 'French (Wallis & Futuna)' },
        { langabr: 'fr', local: 'fr-YT', language: 'French (Mayotte)' },
        { langabr: 'fur', local: 'fur-IT', language: 'Friulian (Italy)' },
        { langabr: 'fy', local: 'fy-NL', language: 'Western Frisian (Netherlands)' },
        { langabr: 'ga', local: 'ga-IE', language: 'Irish (Ireland)' },
        { langabr: 'gd', local: 'gd-GB', language: 'Scottish Gaelic (United Kingdom)' },
        { langabr: 'gl', local: 'gl-ES', language: 'Galician (Spain)' },
        { langabr: 'gsw', local: 'gsw-CH', language: 'Swiss German (Switzerland)' },
        { langabr: 'gsw', local: 'gsw-FR', language: 'Swiss German (France)' },
        { langabr: 'gsw', local: 'gsw-LI', language: 'Swiss German (Liechtenstein)' },
        { langabr: 'gu', local: 'gu-IN', language: 'Gujarati (India)' },
        { langabr: 'guz', local: 'guz-KE', language: 'Gusii (Kenya)' },
        { langabr: 'gv', local: 'gv-IM', language: 'Manx (Isle of Man)' },
        { langabr: 'ha', local: 'ha-GH', language: 'Hausa (Ghana)' },
        { langabr: 'ha', local: 'ha-NE', language: 'Hausa (Niger)' },
        { langabr: 'ha', local: 'ha-NG', language: 'Hausa (Nigeria)' },
        { langabr: 'haw', local: 'haw-US', language: 'Hawaiian (United States)' },
        { langabr: 'he', local: 'he-IL', language: 'Hebrew (Israel)' },
        { langabr: 'hi', local: 'hi-IN', language: 'Hindi (India)' },
        { langabr: 'hr', local: 'hr-BA', language: 'Croatian (Bosnia & Herzegovina)' },
        { langabr: 'hr', local: 'hr-HR', language: 'Croatian (Croatia)' },
        { langabr: 'hsb', local: 'hsb-DE', language: 'Upper Sorbian (Germany)' },
        { langabr: 'hu', local: 'hu-HU', language: 'Hungarian (Hungary)' },
        { langabr: 'hy', local: 'hy-AM', language: 'Armenian (Armenia)' },
        { langabr: 'ig', local: 'ig-NG', language: 'Igbo (Nigeria)' },
        { langabr: 'ii', local: 'ii-CN', language: 'Sichuan Yi (China)' },
        { langabr: 'in', local: 'in-ID', language: 'Indonesian (Indonesia)' },
        { langabr: 'is', local: 'is-IS', language: 'Icelandic (Iceland)' },
        { langabr: 'it', local: 'it-CH', language: 'Italian (Switzerland)' },
        { langabr: 'it', local: 'it-IT', language: 'Italian (Italy)' },
        { langabr: 'it', local: 'it-SM', language: 'Italian (San Marino)' },
        { langabr: 'it', local: 'it-VA', language: 'Italian (Vatican City)' },
        { langabr: 'iw', local: 'iw-IL', language: 'Hebrew (Israel)' },
        { langabr: 'ja', local: 'ja-JP', language: 'Japanese (Japan)' },
        { langabr: 'jgo', local: 'jgo-CM', language: 'Ngomba (Cameroon)' },
        { langabr: 'jmc', local: 'jmc-TZ', language: 'Machame (Tanzania)' },
        { langabr: 'ka', local: 'ka-GE', language: 'Georgian (Georgia)' },
        { langabr: 'kab', local: 'kab-DZ', language: 'Kabyle (Algeria)' },
        { langabr: 'kam', local: 'kam-KE', language: 'Kamba (Kenya)' },
        { langabr: 'kde', local: 'kde-TZ', language: 'Makonde (Tanzania)' },
        { langabr: 'kea', local: 'kea-CV', language: 'Kabuverdianu (Cape Verde)' },
        { langabr: 'khq', local: 'khq-ML', language: 'Koyra Chiini (Mali)' },
        { langabr: 'ki', local: 'ki-KE', language: 'Kikuyu (Kenya)' },
        { langabr: 'kk', local: 'kk-KZ', language: 'Kazakh (Kazakhstan)' },
        { langabr: 'kkj', local: 'kkj-CM', language: 'Kako (Cameroon)' },
        { langabr: 'kl', local: 'kl-GL', language: 'Kalaallisut (Greenland)' },
        { langabr: 'kln', local: 'kln-KE', language: 'Kalenjin (Kenya)' },
        { langabr: 'km', local: 'km-KH', language: 'Khmer (Cambodia)' },
        { langabr: 'kn', local: 'kn-IN', language: 'Kannada (India)' },
        { langabr: 'ko', local: 'ko-KP', language: 'Korean (North Korea)' },
        { langabr: 'ko', local: 'ko-KR', language: 'Korean (South Korea)' },
        { langabr: 'kok', local: 'kok-IN', language: 'Konkani (India)' },
        { langabr: 'ks', local: 'ks-IN', language: 'Kashmiri (India)' },
        { langabr: 'ksb', local: 'ksb-TZ', language: 'Shambala (Tanzania)' },
        { langabr: 'ksf', local: 'ksf-CM', language: 'Bafia (Cameroon)' },
        { langabr: 'ksh', local: 'ksh-DE', language: 'Colognian (Germany)' },
        { langabr: 'kw', local: 'kw-GB', language: 'Cornish (United Kingdom)' },
        { langabr: 'ky', local: 'ky-KG', language: 'Kyrgyz (Kyrgyzstan)' },
        { langabr: 'lag', local: 'lag-TZ', language: 'Langi (Tanzania)' },
        { langabr: 'lb', local: 'lb-LU', language: 'Luxembourgish (Luxembourg)' },
        { langabr: 'lg', local: 'lg-UG', language: 'Ganda (Uganda)' },
        { langabr: 'lt', local: 'lt-LT', language: 'Lithuanian (Lithuania)' },
        { langabr: 'lv', local: 'lv-LV', language: 'Latvian (Latvia)' },
        { langabr: 'mk', local: 'mk-MK', language: 'Macedonian (Macedonia)' },
        { langabr: 'ms', local: 'ms-MY', language: 'Malay (Malaysia)' },
        { langabr: 'mt', local: 'mt-MT', language: 'Maltese (Malta)' },
        { langabr: 'nl', local: 'nl-BE', language: 'Dutch (Belgium)' },
        { langabr: 'nl', local: 'nl-NL', language: 'Dutch (Netherlands)' },
        { langabr: 'no', local: 'no-NO', language: 'Norwegian (Norway)' },
        { langabr: 'no', local: 'no-NO-NY', language: 'Norwegian (Norway Nynorsk)' },
        { langabr: 'pl', local: 'pl-PL', language: 'Polish (Poland)' },
        { langabr: 'pt', local: 'pt-AO', language: 'Portuguese (Angola)' },
        
        { langabr: 'pt', local: 'pt-CH', language: 'Portuguese (Switzerland)' },
        { langabr: 'pt', local: 'pt-CV', language: 'Portuguese (Cape Verde)' },
        { langabr: 'pt', local: 'pt-GQ', language: 'Portuguese (Equatorial Guinea)' },
        { langabr: 'pt', local: 'pt-GW', language: 'Portuguese (Guinea-Bissau)' },
        { langabr: 'pt', local: 'pt-LU', language: 'Portuguese (Luxembourg)' },
        { langabr: 'pt', local: 'pt-MO', language: 'Portuguese (Macau SAR China)' },
        { langabr: 'pt', local: 'pt-MZ', language: 'Portuguese (Mozambique)' },
        { langabr: 'pt', local: 'pt-PT', language: 'Portuguese (Portugal)' },
        { langabr: 'pt', local: 'pt-ST', language: 'Portuguese (São Tomé & Príncipe)' },
        { langabr: 'pt', local: 'pt-TL', language: 'Portuguese (Timor-Leste)' },
        { langabr: 'ro', local: 'ro-RO', language: 'Romanian (Romania)' },
        { langabr: 'ru', local: 'ru-BY', language: 'Russian (Belarus)' },
        { langabr: 'ru', local: 'ru-KG', language: 'Russian (Kyrgyzstan)' },
        { langabr: 'ru', local: 'ru-KZ', language: 'Russian (Kazakhstan)' },
        { langabr: 'ru', local: 'ru-MD', language: 'Russian (Moldova)' },
        { langabr: 'ru', local: 'ru-RU', language: 'Russian (Russia)' },
        { langabr: 'ru', local: 'ru-UA', language: 'Russian (Ukraine)' },
        { langabr: 'sk', local: 'sk-SK', language: 'Slovak (Slovakia)' },
        { langabr: 'sl', local: 'sl-SI', language: 'Slovenian (Slovenia)' },
        { langabr: 'sq', local: 'sq-AL', language: 'Albanian (Albania)' },
        { langabr: 'sr', local: 'sr-BA', language: 'Serbian (Bosnia and Herzegovina)' },
        { langabr: 'sr', local: 'sr-CS', language: 'Serbian (Serbia and Montenegro)' },
        { langabr: 'sr', local: 'sr-ME', language: 'Serbian (Montenegro)' },
        { langabr: 'sr', local: 'sr-RS', language: 'Serbian (Serbia)' },
        { langabr: 'sv', local: 'sv-SE', language: 'Swedish (Sweden)' },
        { langabr: 'th', local: 'th-TH', language: 'Thai (Thailand)' },
        { langabr: 'th', local: 'th-TH-TH', language: 'Thai (Thailand)' },
        { langabr: 'tr', local: 'tr-TR', language: 'Turkish (Turkey)' },
        { langabr: 'uk', local: 'uk-UA', language: 'Ukrainian (Ukraine)' },
        { langabr: 'vi', local: 'vi-VN', language: 'Vietnamese (Vietnam)' },
        { langabr: 'zh', local: 'zh-Hans', language: 'Chinese (Simplified) (zh-Hans)' },
        { langabr: 'zh', local: 'zh-Hans-HK', language: 'Chinese (Simplified, Hong Kong SAR China)' },
        { langabr: 'zh', local: 'zh-Hans-MO', language: 'Chinese (Simplified, Macau SAR China)' },
        { langabr: 'zh', local: 'zh-Hans-SG', language: 'Chinese (Simplified, Singapore)' },
        { langabr: 'zh', local: 'zh-Hant', language: 'Chinese (Traditional)' },
        { langabr: 'zh', local: 'zh-Hant-HK', language: 'Chinese (Traditional, Hong Kong SAR China)' },
        { langabr: 'zh', local: 'zh-Hant-MO', language: 'Chinese (Traditional, Macau SAR China)' },
        { langabr: 'zh', local: 'zh-Hant-TW', language: 'Chinese (Traditional, Taiwan)' },
        { langabr: 'zh', local: 'zh-HK', language: 'Chinese (Simplified, China) (zh-Hans-CN)' },
        { langabr: 'zu', local: 'zu-ZA', language: 'Zulu (South Africa)' }
    ]
}
export const LocalsAvail = () => {
    let avail = ['es', 'en'];
    // let locals=Locals().filter((value)=>value.abrlang=);
    let locals = Locals().filter(item1 =>
        avail.some(item2 => 
            item2.match(item1.langabr)
        )
    );
   let local_ret= locals.map((item)=>{
        return {
            value: item.local,
            label: item.local+' - '+ item.language
        }
    })
    return local_ret
}
export const FN=(numb)=>{
    if(!numb)
        return numb
    return  new Intl.NumberFormat(Local()).format(numb)    
}